### ISSUE TITLE
Internationalization/Translation of docs

### ISSUE THREAD

**Issue by kelle** [astropy/project#30] opened 2019-11-19 15:59 UTC
How to translate the docs? This is a very tough problem.

**Comment by astrofrog** [comment] 2019-12-18 10:33
This was discussed briefly in Socorro - the decision was to wait a little to see what is done by e.g. Numpy/NumFOCUS, since it was reported that there are some efforts underway in that direction.

**Comment by astrofrog** [comment] 2019-12-18 10:42
Duplicate of https://github.com/astropy/project/issues/13

**Closed by astrofrog** 2019-12-18 10:42 UTC
Labels: infrastructure :package:
